routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('products.index');
});

//Route::resource('products', '\App\Http\Controllers\ProductsController');
Route::name('products.')->group(function () {
    Route::get('/products/{id}/show', '\App\Http\Controllers\ProductsController@show')->name('show');
    Route::get('/products/create', '\App\Http\Controllers\ProductsController@create')->name('create');
    Route::get('/products/index', '\App\Http\Controllers\ProductsController@index')->name('index');
    Route::post('/products/store', '\App\Http\Controllers\ProductsController@store')->name('store');
    Route::get('/products/{id}/edit', '\App\Http\Controllers\ProductsController@edit')->name('edit');
    Route::post('/products/{id}/update', '\App\Http\Controllers\ProductsController@update')->name('update');
    Route::get('/products/{id}/destroy', '\App\Http\Controllers\ProductsController@destroy')->name('destroy');
    Route::get('/products/{id}/view', '\App\Http\Controllers\ProductsController@view')->name('view');
    Route::get('/products/{id}/add-image', '\App\Http\Controllers\ProductsController@addImage')->name('add-image');
    Route::get('/products/{id}/update-image', '\App\Http\Controllers\ProductsController@updateImage')->name('update-image');
});

Route::name('images.')->group(function () {
    Route::get('/images/create-image', '\App\Http\Controllers\ImagesController@createImage')->name('create-image');
    Route::post('/images/upload-image', '\App\Http\Controllers\ImagesController@uploadImage')->name('upload-image');
});

Route::get('/products/{productId}/add-to-cart', '\App\Http\Controllers\ProductsController@getAddtoCart')->name('add-to-cart');

app/Models/Products.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Products extends Model
{
    use SoftDeletes;

    protected $table = "products";

    protected $fillable = [
        'name', 'price', 'description', 'brand_id'
    ];

    public function brand(){
        return $this->hasOne(Brands::class, 'id', 'brand_id');
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Cart;
use App\Models\Brands;
use App\Models\Images;
use App\Models\Products;
use Illuminate\Http\File;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;
use Laracasts\Flash\Flash;

class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $product = Products::select('id', 'name', 'brand_id', 'price', 'description')->get();
        return view('products.index', ['products' => $product]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create', ['brands' => Brands::pluck('name', 'id')]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->input();

        Products::create($input);

        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Products::find($id);
        if (empty($product)) {
            return redirect(route('404'));
        }

        return view('products.detail')->with('product', $product);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Products::find($id);
        if (empty($product)) {
            return redirect(route('404'));
        }

        return view('products.edit')->with(['product' => $product, 'brands' => Brands::pluck('name', 'id')]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->input();
        $product = Products::find($id);
        if (empty($product)) {
            return redirect(route('404'));
        }
        $product->update($input);


        return redirect()->route('products.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Products::find($id);

        if (empty($product)) {
            return redirect()->route('products.index');
        }

        $product->delete();

        return redirect()->route('products.index');
    }

    public function view($id){
        $product = Products::find($id);

        if (empty($product)) {
            return redirect()->route('products.index');
        }

        return view('products.detail', ['product' => $product]);
    }

    public function addImage($productId){
        $product = Products::find($productId);
        $files = Images::select('id', 'name', 'location')->get();

        return view('products.add-image', ['files' => $files, 'product' => $product]);
    }

    public function updateImage(Request $request, $productId){
        return view('products.add-image');
    }

    public function getAddtoCart(Request $request, $id)
    {
        $product = Products::find($id);
        $oldCart = Session('cart') ? Session::get('cart') : null;
        $cart = new Cart($oldCart);
        $cart->add($product, $id);
        $request->session()->put('cart', $cart);
        return view('products.detail')->with('product', $product);
    }
}

resources/views/products/add-image.blade.php
<x-master>
    <h1>Add Image For Product</h1>
    <div class="container">
        <div class="table-bordered">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">name</th>
                    <th scope="col">Image</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($files as $file)
                    <tr>
                        <td class="text-center-fixed">{{data_get($file, 'name')}}</td>
                        <td><img src="{{asset('storage/'.data_get($file, 'location'))}}" alt="" height="100px"/></td>
                        <td><a class="btn btn-default text-white bg-blue-active"
                               href="{{route("products.update-image", data_get($product, 'id'))}}">Add</a></td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

</x-master>

resources/views/products/create.blade.php
<x-master>
    <form method="post" action="{{route('products.store')}}">
        <div class="container">
            <div class="inputBox">
                <input class="form-control" name="name" placeholder="ProductName" type="text" required="">
            </div>
            <div class="inputBox" >
                <input class="form-control" name="price" placeholder="Price" type="text" required="">
            </div>
            <select name="brand_id" class="form-control">
                <option value="">Select Brand</option>
                @foreach($brands as $id => $brand)
                    <option value="{{$id}}">{{$brand}}</option>
                @endforeach
            </select>
            <div class="inputBox">
                <textarea class="form-control" name="description" placeholder="Description" type="text" required=""></textarea>
            </div>
            <div class="inputBox">
                <input class="btn btn-default text-white bg-danger" type="submit" name="create" value="Create">{{ csrf_field() }}
                <a class="btn btn-default text-white bg-danger" href="{{route('products.index')}}">Back</a>
            </div>
        </div>
    </form>
</x-master>

resources/views/products/edit.blade.php
<x-master>
    <form method="post" action="{{route('products.update', data_get($product, 'id'))}}">
        <div class="container">
            <div class="inputBox">
                <input class="form-control" name="name" placeholder="ProductName" type="text" value="{{data_get($product, 'name')}}">
            </div>
            <div class="inputBox" >
                <input class="form-control" name="price" placeholder="Price" type="text" value="{{data_get($product, 'price')}}">
            </div>
            <select name="brand_id" class="form-control" value="{{data_get($product, 'brand_id')}}">
                <option value="">Select Brand</option>
                @foreach($brands as $id => $brand)
                    <option value="{{$id}}">{{$brand}}</option>
                @endforeach
            </select>
            <div class="inputBox">
                <input class="form-control" name="description" placeholder="Description" type="text" value="{{data_get($product, 'description')}}">
            </div>
            <div class="form-group col-sm-12">
                <input class="btn btn-default text-white bg-success" type="submit" name="update" value="Update">{{ csrf_field() }}
                <a class="btn btn-default text-white bg-danger" href="{{route('products.index')}}">Back</a>
            </div>
        </div>
    </form>
</x-master>

resources/views/products/index.blade.php
<x-master>
    <h1>Products</h1>
    <a class="btn btn-default text-white bg-blue-active" href="{{route("products.create")}}">Create</a>
    <a class="btn btn-default text-white bg-blue-active" href="{{route("images.create-image")}}">Upload Image</a>
    <div class="container">
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">name</th>
                <th scope="col">Brand</th>
                <th scope="col">Price</th>
                <th scope="col">Description</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($products as $product)
                <tr>
                    <th scope="row">{{data_get($product, 'id')}}</th>
                    <td class="text-center-fixed">{{data_get($product, 'name')}}</td>
                    <td class="text-center-fixed">{{data_get($product->brand, 'name')}}</td>
                    <td class="text-center-fixed">{{data_get($product, 'price')}}</td>
                    <td class="text-center-fixed col-3">{{data_get($product, 'description')}}</td>
                    <td class="text-center-fixed">
                        <a class="btn btn-default text-white bg-blue-active"
                           href="{{route("products.view", data_get($product, 'id'))}}">View</a>
                        <a class="btn btn-default text-white bg-blue-active"
                           href="{{route("products.add-image", data_get($product, 'id'))}}">Add Image</a>
                        <a class="btn btn-default text-white bg-blue-active"
                           href="{{route("products.edit", data_get($product, 'id'))}}">Edit</a>
                        <a class="btn btn-default text-white bg-danger"
                           href="{{route("products.destroy", data_get($product, 'id'))}}">Delete</a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</x-master>